adhoc = true

[prefix]
url_prefix = "https://dinner.sea.com"
token_prefix = "Token "

[runtime]
retry_times = 5
menu_refresh_interval_seconds = 600

[order_time]
hour = 23
minutes = 45
seconds = 0

[grayscale]
percentage = 50