adhoc = true
unit_test = false

[prefix]
url_prefix = "https://dinner.sea.com"
token_prefix = "Token "

[runtime]
retry_times = 5
menu_refresh_interval_seconds = 600

[order_time]
hour = 4
minutes = 36
seconds = 0

[grayscale]
percentage = 50