adhoc = false

[prefix]
url_prefix = "https://dinner.sea.com"
token_prefix = "Token "

[runtime]
retry_times = 5
retry_offset_seconds = 180
batch_retry_cooldown_seconds = 1

[order_time]
hour = 12
minutes = 30
seconds = 0

[grayscale]
percentage = 50