name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_DB_USERNAME: ${{env.TEST_DB_USERNAME}}
      TEST_DB_PASSWORD: ${{env.TEST_DB_PASSWORD}}
      TEST_DB_URL: ${{env.TEST_DB_URL}}
      TEST_DB_NAME: ${{env.TEST_DB_NAME}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run coverage in Processors
        working-directory: ./Processors
        run: go test -coverprofile=coverage.out -covermode=atomic
      - name: Run coverage in Bot
        working-directory: ./Bot
        run: go test -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2