name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run coverage in Processors
        working-directory: ./Processors
        env:
          TEST_DB_USERNAME: ${{secrets.TEST_DB_USERNAME}}
          TEST_DB_PASSWORD: ${{secrets.TEST_DB_PASSWORD}}
          TEST_DB_URL: ${{secrets.TEST_DB_URL}}
          TEST_DB_NAME: ${{secrets.TEST_DB_NAME}}
          AES_KEY: ${{secrets.AES_KEY}}
          TOKEN: ${{secrets.TOKEN}}
          TEST_REDIS_URL: ${{secrets.TEST_REDIS_URL}}
          TEST_REDIS_PORT: ${{secrets.TEST_REDIS_PORT}}
          TEST_REDIS_PASSWORD: ${{secrets.TEST_REDIS_PASSWORD}}
          TEST_NEWRELIC_KEY: ${{secrets.TEST_NEWRELIC_KEY}}
        run: go test -coverprofile=coverage.out -covermode=atomic
      - name: Run coverage in Bot
        working-directory: ./Bot
        env:
          TEST_DB_USERNAME: ${{secrets.TEST_DB_USERNAME}}
          TEST_DB_PASSWORD: ${{secrets.TEST_DB_PASSWORD}}
          TEST_DB_URL: ${{secrets.TEST_DB_URL}}
          TEST_DB_NAME: ${{secrets.TEST_DB_NAME}}
          AES_KEY: ${{secrets.AES_KEY}}
          TOKEN: ${{secrets.TOKEN}}
          REDIS_URL: ${{secrets.REDIS_URL}}
          REDIS_PORT: ${{secrets.REDIS_PORT}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
          TEST_REDIS_URL: ${{secrets.TEST_REDIS_URL}}
          TEST_REDIS_PORT: ${{secrets.TEST_REDIS_PORT}}
          TEST_REDIS_PASSWORD: ${{secrets.TEST_REDIS_PASSWORD}}
          TEST_NEWRELIC_KEY: ${{secrets.TEST_NEWRELIC_KEY}}
        run: go test -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2